---
- name: Create and Use Templates to Create Custumised Configuration Files
  hosts: database
  become: yes
  tasks:
    
    - name: Template server_list.j2 to server.txt + configure file
      template:
        src: server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        mode: '0600'
        setype: net_conf_t
