---
- name: Use conditionals to control play execution
  hosts: all
  become: yes
  tasks:

    - name: Set vm.swappiness to 10 in /etc/sysctl.conf if more than 2048 ram
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_memory_mb.real.total > 2048

    
    - name: Show error msg if less than 2048 ram
      debug:
        msg: "{{ 'Server memory less than 2048MB' }}"
      when: ansible_memory_mb.real.total < 2048
