- name: Make sure lvm is installed on machines
  yum:
    name: 'lvm*'
    state: present


- name: Create a primary partition for lvm
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 800m


- name: Create a volume group on top of /dev/sdb1
  lvg:
    vg: vg_database
    pvs: /dev/sdb1


- name: Create a logical volume on top of vg_database
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512
        

- name: Create xfs filesystem on lv
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql


- name: Create directory for the  mount
  file:
    path: /mnt/mysql_backups
    state: directory
    mode : '0755'


- name: Mount lv_mysql on /mnt/mysql_backups
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted


# NEED TO CHECK THIS PART -> IT AINT WORKING

- name: Download sources
  get_url:
    url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    dest: /opt/mysql


- name: Install package
  yum:
    name: /opt/mysql/mysql-community-release-el7-5.noarch.rpm
    state: present


- name: Install MySQL
  yum:
    name: mysql-server
    state: installed



#THE PROBLOMATIC PART ENDS HERE


- name: Configure firewall to allow incoming traffic on MySQL port tcp 3306
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled


- name: Set MySQL root password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ database_password }}'
    state: present

